### ISSUE TITLE
Webpack.js is not currently supported well with SwiftWasm

### ISSUE THREAD

**Issue by MaxDesiatov** [JoeMatt/SwiftWasmDemo#1]
@JoeMatt Forgive me the intrusion, but I noticed that you used our outdated template. It wasn't updated since April, and we should have updated our docs for it, see https://github.com/swiftwasm/swift-webpack-template/issues/1.

In the meantime, I recommend having a look at something like [tokamak-todo-example](https://github.com/TokamakUI/tokamak-todo-example) or just [plain `carton init` as described in this guide](https://book.swiftwasm.org/getting-started/browser-app.html) if you'd like to start from scratch. I hope that makes your experience much more smooth!

**Comment by JoeMatt** [comment]
> @JoeMatt Forgive me the intrusion, but I noticed that you used our outdated template. It wasn't updated since April, and we should have updated our docs for it, see https://github.com/swiftwasm/swift-webpack-template/issues/1.
> 
> 
> 
> In the meantime, I recommend having a look at something like [tokamak-todo-example](https://github.com/TokamakUI/tokamak-todo-example) or just [plain `carton init` as described in this guide](https://book.swiftwasm.org/getting-started/browser-app.html) if you'd like to start from scratch. I hope that makes your experience much more smooth!

Thanks for the tips Max!

Was cloning a bunch of WASM demos to read up on the progress, will look at these updates examples as well. Thanks!
